"""create evaluations table

Revision ID: 7ad0be10ec3a
Revises: e2664c4d1557
Create Date: 2026-08-11 02:23:44.977927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad0be10ec3a'
down_revision = 'e2664c4d1557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('masculino', 'femenino', 'otro', name='evaluation_gender', native_enum=False, length=20), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('heart_disease', sa.Boolean(), nullable=False),
    sa.Column('ever_married', sa.Enum('yes', 'no', name='evaluation_ever_married', native_enum=False, length=10), nullable=False),
    sa.Column('work_type', sa.Enum('private', 'govt_job', 'self_employed', 'children', 'never_worked', name='evaluation_work_type', native_enum=False, length=20), nullable=False),
    sa.Column('residence_type', sa.Enum('urban', 'rural', name='evaluation_residence_type', native_enum=False, length=10), nullable=False),
    sa.Column('avg_glucose_level', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('smoking_status', sa.Enum('formerly_smoked', 'never_smoked', 'smokes', 'unknown', name='evaluation_smoking_status', native_enum=False, length=20), nullable=False),
    sa.Column('prediction_class', sa.Integer(), nullable=False),
    sa.Column('prediction_probability', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prediction_class IN (0, 1)', name='ck_evaluations_prediction_class'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_patient_id'), 'evaluations', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_patient_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###